name: ecommerce_store
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.6

  # UI Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular_italic.otf
          weight: 400
        - asset: assets/fonts/coolvetica_regular.otf
          style: italic

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/t-store-splash-logo-black.png
  image_dark: assets/logos/t-store-splash-logo-white.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/t-store-splash-logo-black.png
    image_dark: assets/logos/t-store-splash-logo-white.png

  web: false
